fail_on_error: true
output_folder: "./out"

webpack:
  bundle: "./src/main.a36d99ae.chunk.js"
  sourcemap: "./src/main.a36d99ae.chunk.js.map"
mixins:
  - "./mixins/**/*.mixin.yml"
libs:
  - "./mixins/globals.ts"
